esp32adc1_sr=22000
esp32adc1_avg=32



expected_hz=3900 # 4000
conversion_eff=0.97

hv_v_adc=esp32adc1
hv_v_ch=3
hv_v_rh=200e3        # upper resistor of voltage divider
hv_v_rl=7.5e3        # lower resistor
hv_v_filt_len=60

lv_v_adc=fake
lv_v_ch=3
lv_v_rh=1000e3
lv_v_rl=60e3
lv_v_filt_len=3

# hv_i_ch=255        # there is no HV-side current sensor
hv_i_filt_len=20

lv_i_adc=fake
lv_i_ch=2
lv_i_filt_len=3

ntc_adc=esp32adc1
ntc_ch=7
ntc_filt_len=20