esp32adc1_sr=22000
esp32adc1_avg=32


expected_hz=600 # 833 = 80e3/3/32 (3ch, 32avg, 80khz SR)
conversion_eff=0.95

hv_v_adc=ads1015
hv_v_ch=3
hv_v_rh=200e3        # upper resistor of voltage divider
hv_v_rl=4.7e3        # lower resistor (original: 5.1k)
hv_v_filt_len=20

lv_v_adc=ads1015
lv_v_ch=1
lv_v_rh=23.5e3      # 47k/2
lv_v_rl=1e3
lv_v_filt_len=20

hv_i_adc=ads1015
hv_i_ch=2
hv_i_factor=-20.904  # -(1 / 0.066 /*ACS712-30 sensitivity*/) * (10 + 3.3) / 10. * 1.03734586f
hv_i_midpoint=1.868  # 2.5 * 10. / (10 + 3.3) - 0.0117
hv_i_filt_len=60
iin_min_supply_voltage=6

lv_i_filt_len=60


ntc_adc=esp32adc1
ntc_ch=7		# ADC1_CH7 = GPIO35
ntc_filt_len=20
