adc=esp32adc1
esp32adc1_sr=83333 # 83333 # esp32s3 max=83333, 400000,
esp32adc1_avg=32

expected_hz=730 # 744 = 83333/4/32*8/7
# max_latency=


hv_v_ch=1
hv_v_rh=200e3
hv_v_rl=4.7e3
hv_v_filt_len=60

lv_v_ch=2
lv_v_rh=23.5e3
lv_v_rl=1e3
lv_v_filt_len=60

# iin is a virtual sensor
hv_i_filt_len=60

lv_i_ch=3
lv_i_filt_len=60
lv_i_factor=-4
lv_i_midpoint=0.0

conversion_eff=0.97
power_conversion_eff=0.97

ntc_ch=5
ntc_filt_len=200