# hardware limits, change with care

vin_min=10.5    # prevent board supply under-voltage

lv_max=60
hv_max=85

lv_i_max=35
hv_i_max=30
iout_short=6

p_max=1000     # used for temperature de-rating
temp_max=90
temp_derate=70
