
#esp32adc1_sr=83333
esp32adc1_sr=22000
esp32adc1_avg=32

expected_hz=200     # 451
power_conversion_eff=0.97

hv_v_adc=esp32adc1
hv_v_ch=3
hv_v_rh=200e3        # upper resistor of voltage divider
hv_v_rl=7.5e3        # lower resistor
hv_v_filt_len=60

lv_v_adc=ina226
lv_v_ch=0
lv_v_rh=47e3
lv_v_rl=47e3
lv_v_filt_len=60

# hv_i_ch=255        # there is no HV-side current sensor
hv_i_filt_len=20


lv_i_adc=ina226
lv_i_ch=1
lv_i_factor=-1.0
lv_i_filt_len=60

ntc_adc=esp32adc1
ntc_ch=7
ntc_filt_len=20
