import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const dir = (dirName: string) => [{type: 'autogenerated' as const, dirName}];

const sidebars: SidebarsConfig = {
  guide: dir('guide'),
  reference: dir('reference'),
  internals: dir('internals'),
  lab: dir('lab'),
  development: dir('development'),
};

export default sidebars;
