mcu=esp32s3

skip_assert=1

# I2C bus
i2c_sda=42
i2c_scl=2
i2c_freq=800000
i2c_port=0

# INA226
ina22x_alert=41
ina22x_addr=0b1000000
ina22x_resistor=0.5e-3
ina22x_range=35
ina22x_conv_time_us=1100

# PWM driver
pwm_freq=39000
pwm_driver_logic=HiLi
pwm_hi=21
pwm_li=14
pwm_sd=47
boot_refresh_ns=2000

panel_sd=40

led_WS2812=1
